-- MySQL Script generated by MySQL Workbench
-- czw, 20 wrz 2018, 02:42:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wordpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wordpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordpress` DEFAULT CHARACTER SET utf8 ;
USE `wordpress` ;

-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_purchaser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_purchaser` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `current_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_orders` (
  `id` INT(11) NOT NULL,
  `purchaser_id` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `crc` VARCHAR(60) NOT NULL,
  `current_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_details` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
