-- MySQL Script generated by MySQL Workbench
-- wto, 18 wrz 2018, 15:34:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wordpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wordpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordpress` DEFAULT CHARACTER SET utf8 ;
USE `wordpress` ;

-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_purchasers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_purchasers` (
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `create_time`  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_products` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` INT(11) NOT NULL,
  `create_time`  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordpress`.`wp_studiumpay_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`wp_studiumpay_orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `create_time`  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_wp_studiumpay_orders_wp_studiumpay_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_wp_studiumpay_orders_wp_studiumpay_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `wordpress`.`wp_studiumpay_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `wordpress`.`purchasers_make_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordpress`.`purchasers_make_orders` (
  `purchaser_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`purchaser_id`, `order_id`),
  INDEX `fk_wp_studiumpay_purchasers_has_wp_studiumpay_orders_wp_stu_idx` (`order_id` ASC),
  INDEX `fk_wp_studiumpay_purchasers_has_wp_studiumpay_orders_wp_stu_idx1` (`purchaser_id` ASC),
  CONSTRAINT `fk_wp_studiumpay_purchasers_has_wp_studiumpay_orders_wp_studi`
    FOREIGN KEY (`purchaser_id`)
    REFERENCES `wordpress`.`wp_studiumpay_purchasers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wp_studiumpay_purchasers_has_wp_studiumpay_orders_wp_studi1`
    FOREIGN KEY (`order_id`)
    REFERENCES `wordpress`.`wp_studiumpay_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
